language: php

php:
  - 5.4
  - 5.5
  - hhvm
  
env:
  global:
    - PLUGIN_NAME=ArraySort
    - PLUGIN_PATH=Plugin/ArraySort
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.4
    - secure: YoDdVE9D5A60ZN7veu6rVuDGRxcUKoJARw1Z3tLdcastocyGPv8HkvrUPl01PPuplylksFfIMnfGTF/Fl+41BlfIY1AYdL3eTbnQ2Iny9DDrb0RAZYlbisivRNqwWTz7T4hDiVLKA4qyWRuLu0B6qXJEkEw3o+QV4eSnqnudkFw=
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.5
      env:
        - COVERALLS=1
    - php: 5.5
      env:
        - PHPCS=1
    - php: 5.5
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1

before_script:
  - git clone git://github.com/imsamurai/travis-plugin-build.git --depth 1 travis
  - chmod +x ./travis/*
  - ./travis/before_script.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

notifications:
  email: im.samuray@gmail.com