language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.3.10
  - CAKE_VERSION=2.4.1
  - CAKE_VERSION=master

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../cakephp-arraysort-utility plugins/ArraySort
  - chmod -R 777 ../cakephp/app/tmp
  - set +H

script:
  - ./lib/Cake/Console/cake test ArraySort AllArraySort --stderr